# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/home/nguyenduccanh/shellmap_project/smoframework;/home/nguyenduccanh/shellmap_project/smoframework/build-test")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "Unspecified;simdjson_Development")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>= 2.35)")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_SECTION "net")
set(CPACK_DEBIAN_PACKAGE_SUGGESTS "docker.io, docker-compose")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "smo built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "DEB;RPM;TGZ")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/nguyenduccanh/shellmap_project/smoframework/build-test;smo;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/home/nguyenduccanh/shellmap_project/smoframework/cmake;/home/nguyenduccanh/shellmap_project/smoframework/build-test/_deps/catch2-src/extras")
set(CPACK_NSIS_DISPLAY_NAME "smo 0.0.5")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "smo 0.0.5")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/nguyenduccanh/shellmap_project/smoframework/build-test/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "SMO Team <smo@example.com>")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Secure Mesh Operation runtime")
set(CPACK_PACKAGE_FILE_NAME "smo-0.0.5-x86_64")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/smo-framework/smo")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "smo 0.0.5")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "smo 0.0.5")
set(CPACK_PACKAGE_NAME "smo")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "SMO Contributors")
set(CPACK_PACKAGE_VERSION "0.0.5")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "5")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/home/nguyenduccanh/shellmap_project/smoframework/LICENSE")
set(CPACK_RESOURCE_FILE_README "/home/nguyenduccanh/shellmap_project/smoframework/README.md")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.28/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_BUILDROOT "%{_tmppath}/%{name}-%{version}-%{release}-buildroot")
set(CPACK_RPM_CHANGELOG_FILE "/home/nguyenduccanh/shellmap_project/smoframework/packaging/rpm/changelog")
set(CPACK_RPM_COMPRESSION_LEVEL "19")
set(CPACK_RPM_COMPRESSION_TYPE "zstd")
set(CPACK_RPM_DEBUGINFO_PACKAGE "ON")
set(CPACK_RPM_DEFAULT_DIR_PERMISSIONS "0755")
set(CPACK_RPM_DEFAULT_FILE_PERMISSIONS "0644")
set(CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST "/usr/include;/usr/lib/cmake;/usr/share/doc")
set(CPACK_RPM_FILE_NAME "smo-0.0.5-1.x86_64")
set(CPACK_RPM_GROUP "root")
set(CPACK_RPM_PACKAGE_ARCHITECTURE "x86_64")
set(CPACK_RPM_PACKAGE_DESCRIPTION_FILE "/home/nguyenduccanh/shellmap_project/smoframework/README.md")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_MAINTAINER "SMO Team <smo@example.com>")
set(CPACK_RPM_PACKAGE_NAME "smo")
set(CPACK_RPM_PACKAGE_RELEASE "1")
set(CPACK_RPM_PACKAGE_REQUIRES "glibc >= 2.35, openssl-libs >= 3.0, systemd")
set(CPACK_RPM_PACKAGE_SUGGESTS "docker, docker-compose, openvpn")
set(CPACK_RPM_PACKAGE_SUMMARY "Secure Mesh Operation runtime")
set(CPACK_RPM_PACKAGE_URL "https://github.com/smo-framework/smo")
set(CPACK_RPM_PACKAGE_VENDOR "SMO Contributors")
set(CPACK_RPM_PACKAGE_VERSION "0.0.5")
set(CPACK_RPM_SPEC_FILE "/home/nguyenduccanh/shellmap_project/smoframework/packaging/rpm/smo.spec")
set(CPACK_RPM_SPEC_INSTALL_POST "/usr/lib/rpm/brp-compress || true")
set(CPACK_RPM_USER "root")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/nguyenduccanh/shellmap_project/smoframework/build-test/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/nguyenduccanh/shellmap_project/smoframework/build-test/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
