# CMake generated Testfile for 
# Source directory: /home/nguyenduccanh/shellmap_project/smoframework/tests
# Build directory: /home/nguyenduccanh/shellmap_project/smoframework/build-test/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[protocol_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_protocol")
set_tests_properties([=[protocol_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;10;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[packet_crypto_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_packet_crypto")
set_tests_properties([=[packet_crypto_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;21;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[replay_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_replay")
set_tests_properties([=[replay_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;32;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[negative_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_negative")
set_tests_properties([=[negative_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;43;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[trust_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_trust")
set_tests_properties([=[trust_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;54;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[governance_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_governance")
set_tests_properties([=[governance_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;65;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[discovery_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_discovery")
set_tests_properties([=[discovery_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;76;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[session_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_session")
set_tests_properties([=[session_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;87;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[session_security_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_session_security")
set_tests_properties([=[session_security_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;98;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[transport_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_transport")
set_tests_properties([=[transport_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;109;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[secure_session_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_secure_session")
set_tests_properties([=[secure_session_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;120;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[p0_s6_e2e]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_p0_s6_e2e")
set_tests_properties([=[p0_s6_e2e]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;133;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[transport_highlevel]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_transport_hl")
set_tests_properties([=[transport_highlevel]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;144;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[fsm_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_fsm")
set_tests_properties([=[fsm_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;155;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[mesh_fsm_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_mesh_fsm")
set_tests_properties([=[mesh_fsm_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;166;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[certificate_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_certificate")
set_tests_properties([=[certificate_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;177;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[identity_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_identity")
set_tests_properties([=[identity_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;188;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[storage_stores]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_storage_stores")
set_tests_properties([=[storage_stores]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;199;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[storage_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_storage")
set_tests_properties([=[storage_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;210;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[crypto_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_crypto")
set_tests_properties([=[crypto_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;221;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[recovery_package_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_recovery_package")
set_tests_properties([=[recovery_package_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;232;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[shamir_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_shamir")
set_tests_properties([=[shamir_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;243;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[error_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_error")
set_tests_properties([=[error_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;254;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[event_store_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_event_store")
set_tests_properties([=[event_store_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;265;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[runtime_context_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_runtime_context")
set_tests_properties([=[runtime_context_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;276;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[history_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_history")
set_tests_properties([=[history_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;287;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[execution_engine_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_execution_engine")
set_tests_properties([=[execution_engine_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;298;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[scheduler_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_scheduler")
set_tests_properties([=[scheduler_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;309;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[contract_model]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_test_contract")
set_tests_properties([=[contract_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;320;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[protocol_compliance]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_pct")
set_tests_properties([=[protocol_compliance]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;338;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[core]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_stub_core")
set_tests_properties([=[core]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;346;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;349;smo_add_legacy_stub;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[protocol]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_stub_protocol")
set_tests_properties([=[protocol]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;346;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;350;smo_add_legacy_stub;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
add_test([=[compiler]=] "/home/nguyenduccanh/shellmap_project/smoframework/build-test/tests/smo_stub_compiler")
set_tests_properties([=[compiler]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;346;add_test;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;351;smo_add_legacy_stub;/home/nguyenduccanh/shellmap_project/smoframework/tests/CMakeLists.txt;0;")
