# CMake generated Testfile for 
# Source directory: /home/nguyenduccanh/shellmap_project/smoframework/core
# Build directory: /home/nguyenduccanh/shellmap_project/smoframework/build-test/core
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("intent")
subdirs("opcode")
subdirs("contract")
subdirs("capability")
subdirs("session")
subdirs("state")
subdirs("errors")
subdirs("crypto")
subdirs("storage")
subdirs("identity")
subdirs("certificate")
subdirs("fsm")
subdirs("transport")
subdirs("discovery")
subdirs("governance")
subdirs("trust")
subdirs("select")
subdirs("network")
subdirs("enroll")
subdirs("authority")
subdirs("mesh")
subdirs("genesis")
subdirs("recovery")
subdirs("bootstrap")
subdirs("runtime")
subdirs("join")
subdirs("consensus")
subdirs("acl")
subdirs("observability")
subdirs("cbor")
